/**
 * @param {boolean} isDark
 */
export function createGameStyles(isDark) {
  const c = isDark
    ? {
        bgPage: "#0f172a",
        bgCard: "#1e293b",
        bgElevated: "#334155",
        text: "#f1f5f9",
        textMuted: "#94a3b8",
        textSubtle: "#64748b",
        border: "#334155",
        borderStrong: "#475569",
        roomPillBg: "#1e293b",
        errorBg: "#450a0a",
        errorBorder: "#7f1d1d",
        errorText: "#fecaca",
        historyInactiveBg: "#1e293b",
        historyActiveBg: "#38bdf8",
        historyActiveText: "#0f172a",
        winSquareBg: "#422006",
        winSquareBorder: "#facc15",
        squareBg: "#1e293b",
        squareBorder: "#475569",
        pieceX: "#60a5fa",
        pieceO: "#f87171",
        danger: "#f87171",
        statusSuccess: "#4ade80",
        accent: "#38bdf8",
      }
    : {
        bgPage: "#f8fafc",
        bgCard: "#fff",
        bgElevated: "#f1f5f9",
        text: "#0f172a",
        textMuted: "#64748b",
        textSubtle: "#94a3b8",
        border: "#e2e8f0",
        borderStrong: "#cbd5e1",
        roomPillBg: "#f1f5f9",
        errorBg: "#fff1f2",
        errorBorder: "#fecdd3",
        errorText: "#9f1239",
        historyInactiveBg: "#f1f5f9",
        historyActiveBg: "#334155",
        historyActiveText: "#fff",
        winSquareBg: "#fefce8",
        winSquareBorder: "#facc15",
        squareBg: "#fff",
        squareBorder: "#e2e8f0",
        pieceX: "#3b82f6",
        pieceO: "#ef4444",
        danger: "#b91c1c",
        statusSuccess: "#16a34a",
        accent: "#2563eb",
      };

  return {
    colors: c,
    container: {
      fontFamily: "system-ui, sans-serif",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "40px 20px",
      backgroundColor: c.bgPage,
      color: c.text,
      minHeight: "100vh",
    },
    header: {
      textAlign: "center",
      marginBottom: "32px",
    },
    title: {
      fontSize: "24px",
      fontWeight: "800",
      margin: "0 0 8px 0",
      color: c.text,
    },
    status: {
      fontSize: "16px",
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: "0.05em",
    },
    board: {
      display: "grid",
      gridTemplateColumns: "repeat(3, 100px)",
      gridTemplateRows: "repeat(3, 100px)",
      gap: "12px",
      marginBottom: "32px",
    },
    square: {
      width: "100px",
      height: "100px",
      border: `2px solid ${c.squareBorder}`,
      borderRadius: "12px",
      fontSize: "36px",
      fontWeight: "800",
      cursor: "pointer",
      transition: "all 0.1s ease",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.squareBg,
    },
    controls: {
      marginBottom: "40px",
      display: "flex",
      flexWrap: "wrap",
      gap: "10px",
      justifyContent: "center",
    },
    resetBtn: {
      padding: "10px 24px",
      backgroundColor: c.bgCard,
      border: `1px solid ${c.border}`,
      borderRadius: "8px",
      fontWeight: "600",
      cursor: "pointer",
      color: c.text,
      boxShadow: isDark ? "none" : "0 1px 2px rgba(0,0,0,0.05)",
    },
    historySection: {
      width: "100%",
      maxWidth: "420px",
      borderTop: `1px solid ${c.border}`,
      paddingTop: "24px",
    },
    historyTitle: {
      fontSize: "14px",
      fontWeight: "600",
      color: c.textSubtle,
      marginBottom: "12px",
      textAlign: "center",
    },
    historyGrid: {
      display: "flex",
      flexWrap: "wrap",
      gap: "10px",
      justifyContent: "center",
    },
    historyItem: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: "6px",
      minWidth: "72px",
    },
    historyMeta: {
      fontSize: "11px",
      fontWeight: "700",
      letterSpacing: "0.04em",
      color: c.textMuted,
      textTransform: "uppercase",
    },
    historyBtn: {
      padding: "4px",
      border: `1px solid ${c.border}`,
      borderRadius: "8px",
      cursor: "pointer",
      backgroundColor: c.historyInactiveBg,
      lineHeight: 0,
    },
    hint: {
      fontSize: "13px",
      color: c.textMuted,
      textAlign: "center",
      marginTop: "8px",
      maxWidth: "400px",
      lineHeight: 1.4,
    },
    errorBox: {
      padding: "16px",
      maxWidth: "420px",
      backgroundColor: c.errorBg,
      border: `1px solid ${c.errorBorder}`,
      borderRadius: "8px",
      color: c.errorText,
      fontSize: "14px",
      textAlign: "center",
    },
    lobbyCard: {
      width: "100%",
      maxWidth: "400px",
      backgroundColor: c.bgCard,
      borderRadius: "12px",
      border: `1px solid ${c.border}`,
      boxShadow: isDark
        ? "0 4px 24px rgba(0,0,0,0.35)"
        : "0 4px 24px rgba(15, 23, 42, 0.06)",
      padding: "28px 24px",
      display: "flex",
      flexDirection: "column",
      alignItems: "stretch",
      gap: "16px",
    },
    lobbyDivider: {
      margin: 0,
      textAlign: "center",
      fontSize: "13px",
      fontWeight: 600,
      color: c.textSubtle,
    },
    joinRow: {
      display: "flex",
      gap: "10px",
      flexWrap: "wrap",
      justifyContent: "center",
    },
    codeInput: {
      flex: "1 1 160px",
      minWidth: "140px",
      padding: "12px 14px",
      fontSize: "18px",
      fontWeight: 700,
      letterSpacing: "0.2em",
      textAlign: "center",
      fontFamily: "ui-monospace, monospace",
      border: `1px solid ${c.border}`,
      borderRadius: "8px",
      textTransform: "uppercase",
      backgroundColor: c.bgPage,
      color: c.text,
    },
    primaryBtn: {
      padding: "12px 20px",
      backgroundColor: isDark ? "#38bdf8" : "#0f172a",
      color: isDark ? "#0f172a" : "#fff",
      border: "none",
      borderRadius: "8px",
      fontWeight: 700,
      fontSize: "15px",
      cursor: "pointer",
    },
    secondaryBtn: {
      padding: "12px 20px",
      backgroundColor: c.bgCard,
      color: c.text,
      border: `1px solid ${c.border}`,
      borderRadius: "8px",
      fontWeight: 700,
      fontSize: "15px",
      cursor: "pointer",
    },
    roomPill: {
      boxSizing: "border-box",
      display: "inline-flex",
      flexDirection: "row",
      alignItems: "center",
      gap: "10px",
      minHeight: "36px",
      height: "36px",
      padding: "0 12px",
      backgroundColor: c.roomPillBg,
      borderRadius: "8px",
      border: `1px solid ${c.border}`,
      color: c.text,
      minWidth: "0",
    },
    roomPillLabel: {
      flex: "0 0 auto",
      fontSize: "10px",
      fontWeight: 700,
      letterSpacing: "0.12em",
      textTransform: "uppercase",
      color: c.textMuted,
      fontFamily: "system-ui, sans-serif",
      lineHeight: 1,
    },
    /** Room code + copy icon + “Copied!” on one line */
    roomPillCodeRow: {
      display: "inline-flex",
      flexDirection: "row",
      alignItems: "center",
      gap: "6px",
      flex: "0 1 auto",
      minWidth: 0,
    },
    roomPillCode: {
      fontFamily: "ui-monospace, monospace",
      fontWeight: 800,
      fontSize: "14px",
      letterSpacing: "0.14em",
      lineHeight: 1,
      whiteSpace: "nowrap",
    },
    roomCopyFeedback: {
      fontSize: "11px",
      fontWeight: 700,
      letterSpacing: "0.04em",
      color: c.statusSuccess,
      whiteSpace: "nowrap",
      animation: "room-copy-pop 0.2s ease-out",
    },
    roomCopyIconBtn: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      flex: "0 0 auto",
      width: "28px",
      height: "28px",
      padding: 0,
      margin: 0,
      border: `1px solid ${c.border}`,
      borderRadius: "6px",
      backgroundColor: c.bgPage,
      color: c.textMuted,
      cursor: "pointer",
    },
    /** Room code + actions in one centered row */
    headerToolbar: {
      display: "flex",
      flexWrap: "wrap",
      alignItems: "center",
      justifyContent: "center",
      gap: "10px",
      marginTop: "14px",
      maxWidth: "100%",
    },
    toolbarBtnDanger: {
      boxSizing: "border-box",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      minHeight: "36px",
      height: "36px",
      padding: "0 14px",
      whiteSpace: "nowrap",
      fontSize: "13px",
      fontWeight: 600,
      borderRadius: "8px",
      border: `1px solid ${isDark ? "#7f1d1d" : "#fecaca"}`,
      backgroundColor: isDark ? "#450a0a" : "#fff1f2",
      color: isDark ? "#fecaca" : "#9f1239",
      cursor: "pointer",
      fontFamily: "inherit",
      lineHeight: 1,
    },
    headline: {
      fontSize: "17px",
      fontWeight: 700,
      letterSpacing: "0.06em",
      textTransform: "uppercase",
      marginTop: "22px",
      marginBottom: 0,
    },
    textBtn: {
      background: "none",
      border: "none",
      color: c.textMuted,
      fontWeight: 600,
      fontSize: "13px",
      cursor: "pointer",
      textDecoration: "underline",
      padding: "4px 0",
    },
  };
}
