export const gameStyles = {
  container: {
    fontFamily: "system-ui, sans-serif",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "40px 20px",
    backgroundColor: "#f8fafc",
    minHeight: "100vh",
  },
  header: {
    textAlign: "center",
    marginBottom: "32px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "800",
    margin: "0 0 8px 0",
    color: "#0f172a",
  },
  status: {
    fontSize: "16px",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  board: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 100px)",
    gridTemplateRows: "repeat(3, 100px)",
    gap: "12px",
    marginBottom: "32px",
  },
  square: {
    width: "100px",
    height: "100px",
    border: "2px solid #e2e8f0",
    borderRadius: "12px",
    fontSize: "36px",
    fontWeight: "800",
    cursor: "pointer",
    transition: "all 0.1s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  controls: {
    marginBottom: "40px",
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    justifyContent: "center",
  },
  resetBtn: {
    padding: "10px 24px",
    backgroundColor: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    fontWeight: "600",
    cursor: "pointer",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
  },
  historySection: {
    width: "100%",
    maxWidth: "324px",
    borderTop: "1px solid #e2e8f0",
    paddingTop: "24px",
  },
  historyTitle: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#94a3b8",
    marginBottom: "12px",
    textAlign: "center",
  },
  historyGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    justifyContent: "center",
  },
  historyBtn: {
    padding: "6px 12px",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
  },
  hint: {
    fontSize: "13px",
    color: "#64748b",
    textAlign: "center",
    marginTop: "8px",
    maxWidth: "360px",
    lineHeight: 1.4,
  },
  errorBox: {
    padding: "16px",
    maxWidth: "420px",
    backgroundColor: "#fff1f2",
    border: "1px solid #fecdd3",
    borderRadius: "8px",
    color: "#9f1239",
    fontSize: "14px",
    textAlign: "center",
  },
  lobbyCard: {
    width: "100%",
    maxWidth: "400px",
    backgroundColor: "#fff",
    borderRadius: "12px",
    border: "1px solid #e2e8f0",
    boxShadow: "0 4px 24px rgba(15, 23, 42, 0.06)",
    padding: "28px 24px",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: "16px",
  },
  lobbyDivider: {
    margin: 0,
    textAlign: "center",
    fontSize: "13px",
    fontWeight: 600,
    color: "#94a3b8",
  },
  joinRow: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  codeInput: {
    flex: "1 1 160px",
    minWidth: "140px",
    padding: "12px 14px",
    fontSize: "18px",
    fontWeight: 700,
    letterSpacing: "0.2em",
    textAlign: "center",
    fontFamily: "ui-monospace, monospace",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    textTransform: "uppercase",
  },
  primaryBtn: {
    padding: "12px 20px",
    backgroundColor: "#0f172a",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontWeight: 700,
    fontSize: "15px",
    cursor: "pointer",
  },
  secondaryBtn: {
    padding: "12px 20px",
    backgroundColor: "#fff",
    color: "#0f172a",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    fontWeight: 700,
    fontSize: "15px",
    cursor: "pointer",
  },
  roomPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "10px",
    marginTop: "10px",
    padding: "8px 14px",
    backgroundColor: "#f1f5f9",
    borderRadius: "8px",
    fontFamily: "ui-monospace, monospace",
    fontWeight: 800,
    fontSize: "15px",
    letterSpacing: "0.12em",
    color: "#0f172a",
  },
  textBtn: {
    background: "none",
    border: "none",
    color: "#64748b",
    fontWeight: 600,
    fontSize: "13px",
    cursor: "pointer",
    textDecoration: "underline",
    padding: "4px 0",
  },
};
